spring.application.name=markethubApplication 
server.port=${PORT:8080} 
spring.datasource.url=${SPRING_DATASOURCE_URL} 
spring.datasource.username=${PGUSER} 
spring.datasource.password=${PGPASSWORD} 
spring.datasource.driver-class-name=org.postgresql.Driver 
spring.jpa.hibernate.ddl-auto=update 
spring.web.cors.allowed-origins=*
